services:
  db:
    image: postgres:15-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - auth_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@db:5432/authdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=authdb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth_network
    restart: unless-stopped

networks:
  auth_network:
    driver: bridge

volumes:
  postgres_data:
