global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"

scrape_configs:
    # Authentication service metrics (running locally)
    - job_name: "auth-service"
      static_configs:
          - targets: ["host.docker.internal:8000"]
      scrape_interval: 5s
      metrics_path: "/metrics"

    # Prometheus itself
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    # Node exporter for system metrics
    - job_name: "node-exporter"
      static_configs:
          - targets: ["node-exporter:9100"]

    # PostgreSQL metrics (if using postgres_exporter)
    # - job_name: 'postgres-exporter'
    #   static_configs:
    #     - targets: ['postgres-exporter:9187']
