"""Add refresh token table

Revision ID: 5b51c69daf7b
Revises: c7e6045d9277
Create Date: 2025-08-25 21:21:38.480604

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5b51c69daf7b"
down_revision: str | Sequence[str] | None = "c7e6045d9277"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
