"""description

Revision ID: 7bae8c635f3a
Revises: 9fcb2abf830e
Create Date: 2025-09-25 20:37:17.187503

"""

# revision identifiers, used by Alembic.
revision: str = "7bae8c635f3a"
down_revision: str | None = "9fcb2abf830e"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes in this migration
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # No changes in this migration
    # ### end Alembic commands ###
