"""Fix created_at default to use current_timestamp

Revision ID: c0424e4b117a
Revises: cb09b7d396e7
Create Date: 2025-08-25 17:07:26.130959

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c0424e4b117a"
down_revision: str | Sequence[str] | None = "cb09b7d396e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
