"""Fix created_at default to use CURRENT_TIMESTAMP

Revision ID: c7e6045d9277
Revises: c0424e4b117a
Create Date: 2025-08-25 17:08:40.181576

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c7e6045d9277"
down_revision: str | Sequence[str] | None = "c0424e4b117a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
