"""Add full_name field to users table

Revision ID: cb09b7d396e7
Revises: f0fcfdca0ace
Create Date: 2025-08-25 16:57:59.380691

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb09b7d396e7"
down_revision: str | Sequence[str] | None = "f0fcfdca0ace"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
